load("@prelude//toolchains:ndk.bzl", "system_cxx_toolchains_from_ndk")
load("@prelude//toolchains:python.bzl", "system_python_bootstrap_toolchain", "system_python_toolchain")
load("@prelude//toolchains:java.bzl", "system_java_toolchains")
load("@prelude//toolchains:dex.bzl", "system_dex_toolchains")
load("@prelude//toolchains:android.bzl", "system_android_toolchains")
load("@prelude//toolchains:kotlin.bzl", "system_kotlin_toolchains")
load("@prelude//toolchains:genrule.bzl", "system_genrule_toolchain")

system_cxx_toolchains_from_ndk(
    name = "cxx",
    visibility = ["PUBLIC"],
)

system_python_toolchain(
    name = "python",
    visibility = ["PUBLIC"],
)

system_python_bootstrap_toolchain(
    name = "python_bootstrap",
    visibility = ["PUBLIC"],
)

system_dex_toolchains(
    name = "dex",
    visibility = ["PUBLIC"],
)

system_java_toolchains(
    java_home = "/Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home",
    visibility = ["PUBLIC"],
)

system_android_toolchains(
    name = "android",
    visibility = ["PUBLIC"],
)

system_kotlin_toolchains(
    name = "kotlin",
    visibility = ["PUBLIC"],
)

system_genrule_toolchain(
    name = "genrule",
    visibility = ["PUBLIC"],
)
