android_library(
  name = 'activity',
  srcs = glob(['*.java']),
  deps = [
    '//res/com/buck/example:res',
    ':util',
  ],
  visibility = [ 'PUBLIC' ],
)

java_library(
  name = 'util',
  srcs = ['util/log.java'],
  deps = [],
  visibility = [ 'PUBLIC' ],
)

kotlin_library(
  name = 'util-kotlin',
  srcs = ['util/log.kt'],
  deps = [],
  visibility = [ 'PUBLIC' ],
)
