platform(
    name = "default_platform",
    constraint_values = [
        "prelude//os/constraints:android",
        "prelude//cpu/constraints:arm64",
    ],
    visibility = ["PUBLIC"],
)

android_binary(
  name = 'app',
  manifest = 'AndroidManifest.xml',
  keystore = ':debug_keystore',
  deps = [
    '//java/com/buck/example:activity',
    '//res/com/buck/example:res',
  ],
  default_target_platform = ":default_platform",
  android_sdk_proguard_config = "none",
  aapt_mode = "aapt2",
)

keystore(
  name = 'debug_keystore',
  store = 'debug.keystore',
  properties = 'debug.keystore.properties',
)
